### ISSUE TITLE
[Error][Access denied] for buildengine-sdk

### ISSUE THREAD

**Issue by magic-debian** [CODeRUS/docker-sailfishos-platform-sdk#1]
Hi CODeRUS,

I've been trying to use your script in order to use the Sailfish SDK with Docker instead of VMWare, yet I'm unable to use it because of the following errors : 

When trying to build build.sh I get the "wrongly used command" error : 

`docker-sailfishos-buildengine/build$ (master) bash build.sh 3.2.10`

When trying to run the run.sh I get the following error (without having successfully built it) : 

```
docker-sailfishos-buildengine$ (master) sudo ./run.sh 
grep: /root/.config/SailfishOS-SDK/qtcreator/mersdk.xml: No such file or directory
Unable to find image 'buildengine-sdk:latest' locally
docker: Error response from daemon: pull access denied for buildengine-sdk, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

Here are my system infos I think might be helpfull : 

mic 0.28.10

Sailfish SDK 3.2.10

Debian 4.19.0-10-amd64

Nevertheless, thank you for your work !

**Comment by CODeRUS** [comment]
hi! you should use https://github.com/CODeRUS/docker-sailfishos-buildengine instead
this repo is for building CI images

**Comment by CODeRUS** [comment]
but!?

install latest Sailfish OS SDK, it contains an official option to use Docker container instead of VirtualBox.

**Comment by magic-debian** [comment]
Thank you for your reply, I am using the latests SDK yet I can't figure how to use the Docker instead of VirtualBox

**Comment by CODeRUS** [comment]
you need to uninstall sdk, install docker, and then install it again. at the early install step you will be prompted to use virtualbox or docker backend
